# Generated by Django 3.2.6 on 2021-08-15 19:41

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='news/default.jpg', upload_to=news.models.upload_to),
        ),
    ]
